FROM node:14-slim

# Create app directory
WORKDIR /usr/src/pwb_fe

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package.json ./
COPY ./react-loadable.json.sample ./react-loadable.json
RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

# Uncomment below line if not using with Docker-compose
#EXPOSE 3000
#CMD [ "npm", "start" ]
